/* spotify_bd_logic_model: */

CREATE TABLE GENERO (
    id_genero INT PRIMARY KEY,
    nome VARCHAR(100)
);

CREATE TABLE ARTISTA (
    id_artista INT PRIMARY KEY,
    nome VARCHAR(500)
);

CREATE TABLE MUSICA (
    popularidade INT,
    id_track VARCHAR(50) PRIMARY KEY,
    nome VARCHAR(1000),
    tempo_ms INT,
    FK_GENERO_id_genero INT,
    FK_ALBUM_id_album INT
);

CREATE TABLE ALBUM (
    id_album INT PRIMARY KEY,
    nome VARCHAR(500)
);

CREATE TABLE PARTICIPACAO (
    FK_MUSICA_id_track VARCHAR(50),
    FK_ARTISTA_id_artista INT,
    tipo_participacao VARCHAR(50),
    PRIMARY KEY (FK_MUSICA_id_track, FK_ARTISTA_id_artista)
);
 
ALTER TABLE MUSICA ADD CONSTRAINT FK_MUSICA_2
    FOREIGN KEY (FK_GENERO_id_genero)
    REFERENCES GENERO (id_genero)
    ON DELETE RESTRICT;
 
ALTER TABLE MUSICA ADD CONSTRAINT FK_MUSICA_3
    FOREIGN KEY (FK_ALBUM_id_album)
    REFERENCES ALBUM (id_album)
    ON DELETE RESTRICT;
 
ALTER TABLE PARTICIPACAO ADD CONSTRAINT FK_PARTICIPACAO_1
    FOREIGN KEY (FK_MUSICA_id_track)
    REFERENCES MUSICA (id_track)
    ON DELETE RESTRICT;
 
ALTER TABLE PARTICIPACAO ADD CONSTRAINT FK_PARTICIPACAO_2
    FOREIGN KEY (FK_ARTISTA_id_artista)
    REFERENCES ARTISTA (id_artista)
    ON DELETE RESTRICT;